=== dmtar/FMI/ASP/Flights_Service/App_Data/Flights.dtd
<!ELEMENT Flight (FlightID,Date,FlightNumber, DepTime, ArrvTime, Status, GroundOp, Airline, Aircraft, AirportInfo)>
<!ELEMENT FlightID (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT FlightNumber (#PCDATA)>
<!ELEMENT DepTime (#PCDATA)>
<!ELEMENT ArrvTime (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT GroundOp (#PCDATA)>
<!ELEMENT Airline (AirlineID, Name, AirlineCountry, Phone, Website)>
    <!ELEMENT AirlineID (#PCDATA) >
    <!ELEMENT Name (#PCDATA) >
    <!ELEMENT AirlineCountry (#PCDATA) >
    <!ELEMENT Phone (#PCDATA) >
    <!ELEMENT Website (#PCDATA) >
        <!ATTLIST Website onlineCheckIN (да | не) #REQUIRED>
        <!ATTLIST Website HotelBooking (да | не) #REQUIRED>
        <!ATTLIST Website CarRental (да | не) #REQUIRED>
<!ELEMENT Aircraft (Description, FirstDate, Length, Height, Wingspan, Diameter, Speed, Manufacturer)>
  <!ATTLIST Aircraft Type CDATA #REQUIRED >
  <!ATTLIST Aircraft Capacity CDATA #REQUIRED >
  <!ATTLIST Aircraft Engines CDATA #REQUIRED >
  <!ELEMENT AircraftID (#PCDATA) >
  <!ELEMENT Description (#PCDATA)>
  <!ELEMENT FirstDate (#PCDATA)>
  <!ELEMENT Length (#PCDATA)>
  <!ELEMENT Height (#PCDATA)>
  <!ELEMENT Wingspan (#PCDATA)>
  <!ELEMENT Diameter (#PCDATA)>
  <!ELEMENT Speed (#PCDATA)>
  <!ELEMENT Manufacturer (#PCDATA)>
<!ELEMENT AirportInfo (AirportID, Code, AirportPhone, Address)>
  <!ATTLIST AirportInfo Airport (излитане | кацане) #REQUIRED >
  <!ELEMENT AirportID (#PCDATA) >
  <!ELEMENT Code (#PCDATA) >
  <!ELEMENT AirportPhone (#PCDATA) >
    <!ATTLIST AirportPhone type (стационарен | мобилен) #REQUIRED >
    <!ATTLIST AirportPhone fax (да | не) #REQUIRED >
  <!ELEMENT Address (City, Street, Postalcode, AirportWebsite) > 
    <!ELEMENT City (#PCDATA) >
    <!ELEMENT Street (#PCDATA) >
    <!ELEMENT Postalcode (#PCDATA) >
    <!ELEMENT AirportWebsite (#PCDATA) >
<!ELEMENT Aircrew (AircrewID, Member)>
    <!ELEMENT AircrewID (#PCDATA)>
    <!ELEMENT Member (MemberName, Country, Age, Years)>
        <!ATTLIST Member Position (пилот | стюардеса) #REQUIRED >
        <!ELEMENT MemberName (#PCDATA) >
        <!ELEMENT Country (#PCDATA) >
        <!ELEMENT Age (#PCDATA) >
        <!ELEMENT Years (#PCDATA) >    
<!ELEMENT TouristInfo (InfoID, Town, Timezone, Currency, AverageTemperature, CityDescription) >
    <!ELEMENT InfoID (#PCDATA)>
    <!ELEMENT Town (#PCDATA) >
    <!ELEMENT Timezone (#PCDATA) >
    <!ELEMENT Currency (#PCDATA) >
    <!ELEMENT AverageTemperature (#PCDATA) >
    <!ELEMENT CityDescription (#PCDATA) >

=== dmtar/FMI/ASP/Flights_Service/App_Data/25.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>25</FlightID>
  <Date>asdasdas</Date>
  <FlightNumber>asdasd</FlightNumber>
  <DepTime>asdasd</DepTime>
  <ArrvTime>asdsad</ArrvTime>
  <Status>asdasd</Status>
  <GroundOp>asdasd</GroundOp>
  <Airline>
    <AirlineID>66</AirlineID>
    <Name>asdasd</Name>
    <AirlineCountry>asdasd</AirlineCountry>
    <Phone>asdasd</Phone>
    <Website OnlineCheckIN="да" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="asdas" Capacity="34" Engines="2">
    <AircraftID>65</AircraftID>
    <Description>asdasdasd</Description>
    <FirstDate></FirstDate>
    <Length></Length>
    <Height></Height>
    <Wingspan></Wingspan>
    <Diameter>asdasdasd</Diameter>
    <Speed></Speed>
    <Manufacturer></Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>55</AirportID>
    <Code>sadasdas</Code>
    <AirportPhone Type="мобилен" Fax="не"></AirportPhone>
    <Address>
      <City></City>
      <Street></Street>
      <Postalcode></Postalcode>
      <AirportWebsite></AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>78</AirportID>
    <Code>asdasd</Code>
    <AirportPhone Type="стационарен" Fax="не"></AirportPhone>
    <Address>
      <City></City>
      <Street></Street>
      <Postalcode></Postalcode>
      <AirportWebsite></AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>44</MemberID>
    <MemberName>dsadasdas</MemberName>
    <Country></Country>
    <Age></Age>
    <Years></Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Flight SYSTEM "flights.dtd">
<Flight>
    <FlightID>1</FlightID>
    <Date>26.1.2014</Date>
    <FlightNumber>TK1028</FlightNumber>
    <DepTime>10:00</DepTime>
    <ArrvTime>11:20</ArrvTime>
    <Status>Регистрация</Status>
    <GroundOp>Голдеър Хендлинг България</GroundOp>
    <Airline>
        <AirlineID>1</AirlineID>
        <Name></Name>
        <AirlineCountry></AirlineCountry>
        <Phone></Phone>
        <Website OnlineCheckIN="да" HotelBooking="да" CarRental="да"></Website>
    </Airline>
    <Aircraft Type="319" Capacity="76" Engines="2">
        <AircraftID>1</AircraftID>
        <Description>Самолет за средни разстояния</Description>
        <FirstDate>29 Август 1995</FirstDate>
        <Length>33,84 m</Length>
        <Height>11,76 m</Height>
        <Wingspan>34,10 m</Wingspan>
        <Diameter>3,95 m</Diameter>
        <Speed>928 km/h</Speed>
        <Manufacturer>Европейски консорциум</Manufacturer>
    </Aircraft>
    <AirportInfo Airport="прекачване">
        <AirportID>1</AirportID>
        <Code>FB123</Code>
        <AirportPhone Type="стационарен" Fax="да">1234</AirportPhone>
        <Address>
            <City>Лондон</City>
            <Street>5 km north of the downtown of Crawley, West Sussex</Street>
            <Postalcode>RH6 0NP</Postalcode>
            <AirportWebsite>test.com</AirportWebsite>
        </Address>
    </AirportInfo>
    <Member Position="пилот">
        <MemberID>1</MemberID>
        <MemberName>Димитър</MemberName>
        <Country>Дишев</Country>
        <Age>22</Age>
        <Years>5</Years>
    </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/8.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>8</FlightID>
  <Date>8.6.2014</Date>
  <FlightNumber>A345</FlightNumber>
  <DepTime>12:45</DepTime>
  <ArrvTime>14:30</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>8</AirlineID>
    <Name>БългарияЕър</Name>
    <AirlineCountry>България</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="да" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="А320" Capacity="350" Engines="2">
    <AircraftID>8</AircraftID>
    <Description></Description>
    <FirstDate>12.12.1996</FirstDate>
    <Length>39.50</Length>
    <Height>12</Height>
    <Wingspan>8.7</Wingspan>
    <Diameter></Diameter>
    <Speed>996.7</Speed>
    <Manufacturer>Холандия</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>15</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="стационарен" Fax="да">123456</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>16</AirportID>
    <Code>ATL</Code>
    <AirportPhone Type="стационарен" Fax="не">012003000</AirportPhone>
    <Address>
      <City>Лондон</City>
      <Street></Street>
      <Postalcode>123</Postalcode>
      <AirportWebsite>www.atlanta-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>14</MemberID>
    <MemberName>Димитър Иванов</MemberName>
    <Country>България</Country>
    <Age>45</Age>
    <Years>20</Years>
  </Member>
  <Member Position="пилот">
    <MemberID>15</MemberID>
    <MemberName>Петър Петров</MemberName>
    <Country>България</Country>
    <Age>42</Age>
    <Years>15</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>7</FlightID>
  <Date>8.6.2014</Date>
  <FlightNumber>Y654</FlightNumber>
  <DepTime>12:45</DepTime>
  <ArrvTime>14:30</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>7</AirlineID>
    <Name>Делта</Name>
    <AirlineCountry>САЩ</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="да" HotelBooking="да" CarRental="не" />
  </Airline>
  <Aircraft Type="B747" Capacity="550" Engines="4">
    <AircraftID>7</AircraftID>
    <Description></Description>
    <FirstDate>1.4.1999</FirstDate>
    <Length>39.50</Length>
    <Height>12</Height>
    <Wingspan>8.7</Wingspan>
    <Diameter></Diameter>
    <Speed>996.7</Speed>
    <Manufacturer>Холандия</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>13</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="стационарен" Fax="да">123456</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>14</AirportID>
    <Code>ATL</Code>
    <AirportPhone Type="стационарен" Fax="не">012003000</AirportPhone>
    <Address>
      <City>Амстердам</City>
      <Street></Street>
      <Postalcode>123</Postalcode>
      <AirportWebsite>www.atlanta-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>12</MemberID>
    <MemberName>Иван Господинов</MemberName>
    <Country>България</Country>
    <Age>45</Age>
    <Years>20</Years>
  </Member>
  <Member Position="стюард">
    <MemberID>13</MemberID>
    <MemberName>Лилия Иванова</MemberName>
    <Country>България</Country>
    <Age>29</Age>
    <Years>5</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>4</FlightID>
  <Date>10.6.2014</Date>
  <FlightNumber>A345</FlightNumber>
  <DepTime>17:43</DepTime>
  <ArrvTime>20:00</ArrvTime>
  <Status></Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>4</AirlineID>
    <Name>УизЕър</Name>
    <AirlineCountry>Англия</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="да" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="А319" Capacity="350" Engines="2">
    <AircraftID>4</AircraftID>
    <Description></Description>
    <FirstDate>1.3.1994</FirstDate>
    <Length>36.20</Length>
    <Height>11.5</Height>
    <Wingspan>9.2</Wingspan>
    <Diameter></Diameter>
    <Speed>990.2</Speed>
    <Manufacturer>САЩ</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>7</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="стационарен" Fax="да">123456</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>8</AirportID>
    <Code>ATL</Code>
    <AirportPhone Type="стационарен" Fax="не">012003000</AirportPhone>
    <Address>
      <City>Лондон</City>
      <Street>Фриилейн стриит</Street>
      <Postalcode>10050</Postalcode>
      <AirportWebsite>www.atlanta-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>6</MemberID>
    <MemberName>Мартин Иванов</MemberName>
    <Country>България</Country>
    <Age>43</Age>
    <Years>15</Years>
  </Member>
  <Member Position="пилот">
    <MemberID>7</MemberID>
    <MemberName>Никола Димитров</MemberName>
    <Country>България</Country>
    <Age>55</Age>
    <Years>25</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>6</FlightID>
  <Date>8.6.2014</Date>
  <FlightNumber>G167</FlightNumber>
  <DepTime>10:45</DepTime>
  <ArrvTime>11:30</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>6</AirlineID>
    <Name>АърФранс</Name>
    <AirlineCountry>Франция</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="да" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="Т19" Capacity="350" Engines="2">
    <AircraftID>6</AircraftID>
    <Description></Description>
    <FirstDate>10.5.1997</FirstDate>
    <Length>34.80</Length>
    <Height>8</Height>
    <Wingspan>9.6</Wingspan>
    <Diameter></Diameter>
    <Speed>898.7</Speed>
    <Manufacturer>Полша</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>11</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="стационарен" Fax="да">123456</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>12</AirportID>
    <Code>MSW</Code>
    <AirportPhone Type="стационарен" Fax="не">3456543</AirportPhone>
    <Address>
      <City>Москва</City>
      <Street></Street>
      <Postalcode>45700</Postalcode>
      <AirportWebsite>www.moscow-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>10</MemberID>
    <MemberName>Росен Трифонов</MemberName>
    <Country>България</Country>
    <Age>45</Age>
    <Years>20</Years>
  </Member>
  <Member Position="пилот">
    <MemberID>11</MemberID>
    <MemberName>Валентин Валентинов</MemberName>
    <Country>България</Country>
    <Age>42</Age>
    <Years>15</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>1</FlightID>
  <Date>8.6.2014</Date>
  <FlightNumber>A345</FlightNumber>
  <DepTime>12:45</DepTime>
  <ArrvTime>14:30</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>1</AirlineID>
    <Name>БългарияЕър</Name>
    <AirlineCountry>България</AirlineCountry>
    <Phone>089898989</Phone>
    <Website OnlineCheckIN="не" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="А320" Capacity="350" Engines="2">
    <AircraftID>1</AircraftID>
    <Description>Самолет за къси разстояния.</Description>
    <FirstDate>12.12.1996</FirstDate>
    <Length>39.50</Length>
    <Height>12</Height>
    <Wingspan>8.7</Wingspan>
    <Diameter>Самолет за къси разстояния.</Diameter>
    <Speed>996.7</Speed>
    <Manufacturer>Холандия</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="излитане">
    <AirportID>1</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="мобилен" Fax="не">089898989</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="кацане">
    <AirportID>2</AirportID>
    <Code>ATL</Code>
    <AirportPhone Type="стационарен" Fax="да">012003000</AirportPhone>
    <Address>
      <City>Атланта</City>
      <Street></Street>
      <Postalcode></Postalcode>
      <AirportWebsite>www.atlanta-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>1</MemberID>
    <MemberName>Димитър Иванов</MemberName>
    <Country>България</Country>
    <Age>45</Age>
    <Years>20</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/123.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>123</FlightID>
  <Date>123</Date>
  <DepTime>123</DepTime>
  <ArrvTime>123</ArrvTime>
  <GroundOp>123</GroundOp>
  <Airline>
    <AirlineID>123</AirlineID>
    <Name>123</Name>
    <AirlineCountry>123</AirlineCountry>
    <Phone>123</Phone>
    <Website OnlineCheckIN="не" HotelBooking="да" CarRental="не" />
  </Airline>
  <Aircraft Type="123" Capacity="123" Engines="123">
    <AircraftID>123</AircraftID>
    <Description></Description>
    <FirstDate></FirstDate>
    <Length></Length>
    <Height></Height>
    <Wingspan></Wingspan>
    <Diameter></Diameter>
    <Speed></Speed>
    <Manufacturer></Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>123</AirportID>
    <Code>123</Code>
    <AirportPhone Type="" Fax="не"></AirportPhone>
    <Address>
      <City></City>
      <Street></Street>
      <Postalcode></Postalcode>
      <AirportWebsite></AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>321</AirportID>
    <Code>321</Code>
    <AirportPhone Type="" Fax="не"></AirportPhone>
    <Address>
      <City></City>
      <Street></Street>
      <Postalcode></Postalcode>
      <AirportWebsite></AirportWebsite>
    </Address>
  </AirportInfo>
  <Member MemberID="33">
    <MemberName>33333</MemberName>
    <Country></Country>
    <Age></Age>
    <Years></Years>
  </Member>
</Flight>
