=== dmtar/FMI/ASP/Flights_Service/App_Data/Flights.dtd
<!ELEMENT Flight (FlightID,Date,FlightNumber, DepTime, ArrvTime, Status, GroundOp, Airline, Aircraft, AirportInfo)>
<!ELEMENT FlightID (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT FlightNumber (#PCDATA)>
<!ELEMENT DepTime (#PCDATA)>
<!ELEMENT ArrvTime (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT GroundOp (#PCDATA)>
<!ELEMENT Airline (AirlineID, Name, AirlineCountry, Phone, Website)>
    <!ELEMENT AirlineID (#PCDATA) >
    <!ELEMENT Name (#PCDATA) >
    <!ELEMENT AirlineCountry (#PCDATA) >
    <!ELEMENT Phone (#PCDATA) >
    <!ELEMENT Website (#PCDATA) >
        <!ATTLIST Website onlineCheckIN (да | не) #REQUIRED>
        <!ATTLIST Website HotelBooking (да | не) #REQUIRED>
        <!ATTLIST Website CarRental (да | не) #REQUIRED>
<!ELEMENT Aircraft (Description, FirstDate, Length, Height, Wingspan, Diameter, Speed, Manufacturer)>
  <!ATTLIST Aircraft Type CDATA #REQUIRED >
  <!ATTLIST Aircraft Capacity CDATA #REQUIRED >
  <!ATTLIST Aircraft Engines CDATA #REQUIRED >
  <!ELEMENT AircraftID (#PCDATA) >
  <!ELEMENT Description (#PCDATA)>
  <!ELEMENT FirstDate (#PCDATA)>
  <!ELEMENT Length (#PCDATA)>
  <!ELEMENT Height (#PCDATA)>
  <!ELEMENT Wingspan (#PCDATA)>
  <!ELEMENT Diameter (#PCDATA)>
  <!ELEMENT Speed (#PCDATA)>
  <!ELEMENT Manufacturer (#PCDATA)>
<!ELEMENT AirportInfo (AirportID, Code, AirportPhone, Address)>
  <!ATTLIST AirportInfo Airport (излитане | кацане) #REQUIRED >
  <!ELEMENT AirportID (#PCDATA) >
  <!ELEMENT Code (#PCDATA) >
  <!ELEMENT AirportPhone (#PCDATA) >
    <!ATTLIST AirportPhone type (стационарен | мобилен) #REQUIRED >
    <!ATTLIST AirportPhone fax (да | не) #REQUIRED >
  <!ELEMENT Address (City, Street, Postalcode, AirportWebsite) > 
    <!ELEMENT City (#PCDATA) >
    <!ELEMENT Street (#PCDATA) >
    <!ELEMENT Postalcode (#PCDATA) >
    <!ELEMENT AirportWebsite (#PCDATA) >
<!ELEMENT Aircrew (AircrewID, Member)>
    <!ELEMENT AircrewID (#PCDATA)>
    <!ELEMENT Member (MemberName, Country, Age, Years)>
        <!ATTLIST Member Position (пилот | стюардеса) #REQUIRED >
        <!ELEMENT MemberName (#PCDATA) >
        <!ELEMENT Country (#PCDATA) >
        <!ELEMENT Age (#PCDATA) >
        <!ELEMENT Years (#PCDATA) >    
<!ELEMENT TouristInfo (InfoID, Town, Timezone, Currency, AverageTemperature, CityDescription) >
    <!ELEMENT InfoID (#PCDATA)>
    <!ELEMENT Town (#PCDATA) >
    <!ELEMENT Timezone (#PCDATA) >
    <!ELEMENT Currency (#PCDATA) >
    <!ELEMENT AverageTemperature (#PCDATA) >
    <!ELEMENT CityDescription (#PCDATA) >

=== dmtar/FMI/ASP/Flights_Service/App_Data/5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>5</FlightID>
  <Date>8.6.2014</Date>
  <FlightNumber>A345</FlightNumber>
  <DepTime>14:50</DepTime>
  <ArrvTime>17:43</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>5</AirlineID>
    <Name>ИзиДжет</Name>
    <AirlineCountry>Франция</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="не" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="F15" Capacity="422" Engines="4">
    <AircraftID>5</AircraftID>
    <Description></Description>
    <FirstDate>4.8.2001</FirstDate>
    <Length>34.50</Length>
    <Height>10</Height>
    <Wingspan>9.7</Wingspan>
    <Diameter>4</Diameter>
    <Speed>1080.5</Speed>
    <Manufacturer>Франция</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="кацане">
    <AirportID>9</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="стационарен" Fax="да">543434</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="излитане">
    <AirportID>10</AirportID>
    <Code>FRA</Code>
    <AirportPhone Type="стационарен" Fax="не">012003000</AirportPhone>
    <Address>
      <City>Париж</City>
      <Street></Street>
      <Postalcode>123</Postalcode>
      <AirportWebsite>www.paris-airport.com</AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>8</MemberID>
    <MemberName>Даниел Георгиев</MemberName>
    <Country>България</Country>
    <Age>38</Age>
    <Years>10</Years>
  </Member>
  <Member Position="пилот">
    <MemberID>9</MemberID>
    <MemberName>Филип Христов</MemberName>
    <Country>България</Country>
    <Age>52</Age>
    <Years>23</Years>
  </Member>
</Flight>

=== dmtar/FMI/ASP/Flights_Service/App_Data/2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Flight SYSTEM "Flights.dtd">
<Flight>
  <FlightID>2</FlightID>
  <Date>1.2.2014</Date>
  <FlightNumber>P112</FlightNumber>
  <DepTime>6:00</DepTime>
  <ArrvTime>8:30</ArrvTime>
  <Status>излетял</Status>
  <GroundOp></GroundOp>
  <Airline>
    <AirlineID>2</AirlineID>
    <Name>БългарияЕър</Name>
    <AirlineCountry>България</AirlineCountry>
    <Phone></Phone>
    <Website OnlineCheckIN="не" HotelBooking="не" CarRental="не" />
  </Airline>
  <Aircraft Type="Боинг" Capacity="500" Engines="4">
    <AircraftID>2</AircraftID>
    <Description>Самолет за дълги разстояния</Description>
    <FirstDate>12.3.1998</FirstDate>
    <Length>56</Length>
    <Height>10</Height>
    <Wingspan>22</Wingspan>
    <Diameter>Самолет за дълги разстояния</Diameter>
    <Speed>1100</Speed>
    <Manufacturer>Германия</Manufacturer>
  </Aircraft>
  <AirportInfo Airport="излитане">
    <AirportID>3</AirportID>
    <Code>SOF</Code>
    <AirportPhone Type="мобилен" Fax="не">123456</AirportPhone>
    <Address>
      <City>София</City>
      <Street>Христофор Колумб</Street>
      <Postalcode>1000</Postalcode>
      <AirportWebsite>www.sofia-airport.bg/</AirportWebsite>
    </Address>
  </AirportInfo>
  <AirportInfo Airport="кацане">
    <AirportID>4</AirportID>
    <Code>TST</Code>
    <AirportPhone Type="стационарен" Fax="да">654321</AirportPhone>
    <Address>
      <City>Лондон</City>
      <Street></Street>
      <Postalcode>123</Postalcode>
      <AirportWebsite></AirportWebsite>
    </Address>
  </AirportInfo>
  <Member Position="пилот">
    <MemberID>2</MemberID>
    <MemberName>Георги Петков</MemberName>
    <Country>България</Country>
    <Age>39</Age>
    <Years>15</Years>
  </Member>
  <Member Position="пилот">
    <MemberID>3</MemberID>
    <MemberName>Петър Петров</MemberName>
    <Country>България</Country>
    <Age>42</Age>
    <Years>15</Years>
  </Member>
</Flight>
